### ISSUE TITLE
Having issues with Ruby 1.9.2-p290

### ISSUE THREAD

**Issue by aboutaaron** [propublica/timeline-setter#29]
Hi,

For whatever reason when I run timeline user ruby 1.9.2 I receive several errors, the first of which being

`/Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:198:in `local': argument out of range (ArgumentError)`

However, this does not happen on 1.8.7. Could this be because 1.8.7 is the system Ruby install and 1.9.2 is via RVM?

**Comment by thejefflarson** [comment]
Yeah we usually use 1.8.7, let me take a look at it.

**Comment by thejefflarson** [comment]
I just tried this, and it worked for me. Can you send along the command you used? And a full stacktrace of the errors?

**Comment by aboutaaron** [comment]
Hey @thejefflarson thanks for replying.

The command issued on both 1.8.7 and 1.9.2 is `timeline-setter -i Lustrum -c ~/desktop/cfa.csv`

Which results in:

```
/Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:198:in `local': argument out of range (ArgumentError)
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:198:in `make_time'
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/time.rb:267:in `parse'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:14:in `block in to_json'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:14:in `each'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:14:in `to_json'
    from (erb):4:in `tmpl'
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/erb.rb:753:in `eval'
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/erb.rb:753:in `result'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:49:in `tmpl'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:26:in `timeline_markup'
    from (erb):10:in `tmpl'
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/erb.rb:753:in `eval'
    from /Users/vesuvius/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/erb.rb:753:in `result'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:49:in `tmpl'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/timeline.rb:33:in `timeline'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:63:in `html'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:85:in `block in compile!'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:84:in `open'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:84:in `compile!'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:50:in `parse_options!'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:7:in `initialize'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/bin/timeline-setter:9:in `new'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/gems/timeline_setter-0.3.0/bin/timeline-setter:9:in `<top (required)>'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/bin/timeline-setter:19:in `load'
    from /Users/vesuvius/.rvm/gems/ruby-1.9.2-p290/bin/timeline-setter:19:in `<main>'
```

Thoughts?

**Comment by thejefflarson** [comment]
Sorry about the silence here, can you post a copy of the csv?
