### ISSUE TITLE
Newbie: "cli.rb:55:in 'initialize': can't convert nil into String (TypeError)"

### ISSUE THREAD

**Issue by Kirkman** [propublica/timeline-setter#39]
I don't know Ruby at all and am only passingly familiar with linux and command line stuff. I installed timeline-setter on my OS X Lion machine with (seemingly) no problems. 

My first attempt to render a very simple csv as a timeline ended up with this error message:

/Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:55:in `initialize': can't convert nil into String (TypeError)
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:55:in`open'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:55:in `sheet'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:59:in`events'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:64:in `html'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:85:in`compile!'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:84:in `open'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:84:in`compile!'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:50:in `parse_options!'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/lib/timeline_setter/cli.rb:7:in`initialize'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/bin/timeline-setter:9:in `new'
    from /Library/Ruby/Gems/1.8/gems/timeline_setter-0.3.0/bin/timeline-setter:9
    from /usr/bin/timeline-setter:19:in`load'
    from /usr/bin/timeline-setter:19

Timeline Setter did output js and css files, but the timeline.html file was empty (0 bytes).

Any idea what is going wrong here?

**Comment by Kirkman** [comment]
I'm an idiot. I overlooked the "-c" flag.
