### ISSUE TITLE
Time.parse error in Ruby 1.9.2

### ISSUE THREAD

**Issue by ashaw** [propublica/timeline-setter#8]
Looks like `Time.parse` is choking the script in 1.9.2

```
/Users/dnguyen/.rvm/gems/ruby-1.9.2-p136/gems/timeline_setter-0.1.0/lib/timeline_setter/timeline.rb:13:in `[]': can't convert Symbol into Integer (TypeError)
    from /Users/dnguyen/.rvm/gems/ruby-1.9.2-p136/gems/timeline_setter-0.1.0/lib/timeline_setter/timeline.rb:13:in `block in to_json'
    from /Users/dnguyen/.rvm/gems/ruby-1.9.2-p136/gems/timeline_setter-0.1.0/lib/timeline_setter/timeline.rb:13:in `sort'
    from /Users/dnguyen/.rvm/gems/ruby-1.9.2-p136/gems/timeline_setter-0.1.0/lib/timeline_setter/timeline.rb:13:in `to_json'
    from (erb):24:in `tmpl'
```

**Comment by ashaw** [comment]
fixed in eef8d346c2e5b001d907
